name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  weather_icons: ^3.0.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  http: ^0.13.5
  json_annotation: ^4.8.0
  build_runner: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
